// This file was automatically generated by UICodeGenerator.cs
// F:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Widget/LoadingWidgetUI.cs
using TMPro;
using UnityEngine.UI;

public class LoadingWidgetUI : UIBinderBase
{
	public Image image;
}