// This file was automatically generated by UICodeGenerator.cs
// D:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/DuelSetupPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class DuelSetupPopupUI : UIBinderBase
{
	public Button btn_9x9;
	public Button btn_13x13;
	public Button btn_19x19;
	public Button btn_close;
}