// This file was automatically generated by UICodeGenerator.cs
// F:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/DuelPageUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class DuelPageUI : UIBinderBase
{
	public Button btn_save;
	public Button btn_exit;
	public TextMeshProUGUI txt_cur_state;
	public TextMeshProUGUI txt_cur_player;
	public TextMeshProUGUI txt_turn_time;
}