// This file was automatically generated by UICodeGenerator.cs
// D:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/SavingPpopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class SavingPpopupUI : UIBinderBase
{
	public GameObject panel_save;
}