// This file was automatically generated by UICodeGenerator.cs
// D:/Project/WeiqiXN/UnityProject/Assets/Scripts/Game/UI/Binder/Page/UserInfoPopupUI.cs
using TMPro;
using UnityEngine;
using UnityEngine.UI;

public class UserInfoPopupUI : UIBinderBase
{
	public TextMeshProUGUI txt_user_id;
	public TextMeshProUGUI txt_win_count;
	public TextMeshProUGUI txt_lose_count;
	public Button btn_close;
}