using System.IO;
using System.Text;
using UnityEngine;

public static class UIBinderGenerator
{
    public readonly static string UI_BINDER_EXPORT_PATH = Path.Combine(Application.dataPath, "Scripts", "Game", "UI", "BinderExport");

    public static void ExportUIBinder(UIBinderInfo binderInfo)
    {
        CSCodeGenerator generator = new CSCodeGenerator();
        generator.AddLine("// This file was automatically generated by UIBinderGenerator.cs");
        generator.AddLine($"// {binderInfo.exportPath.Replace('\\', '/')}");
        generator.AddLine("using UnityEngine.UI;");

        generator.AddLine();

        using (generator.AddBolock($"public class {binderInfo.binderClsName} : UILogicBinder")) {
            foreach (var node in binderInfo.binder.nodeList) {
                generator.AddLine($"public {node.value.GetType().Name} {node.name};");
            }
        }

        if (File.Exists(binderInfo.exportPath)) File.Delete(binderInfo.exportPath);

        Directory.CreateDirectory(Path.GetDirectoryName(binderInfo.exportPath));

        using (var writer = new StreamWriter(binderInfo.exportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }
}
