using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

public static class UIGenerator
{

    public static void ExportUIPageCollection()
    {

    }

    public static void ExportUIWidgetCollection()
    {

    }

    public static void ExportUIScripts(UIComponentBinder uiCompBinder)
    {
        ExportUIBinder(uiCompBinder);
        if (!File.Exists(uiCompBinder.logicExportPath)) {
            ExportUILogic(uiCompBinder);
        }

        AssetDatabase.Refresh();
    }

    private static void ExportUIBinder(UIComponentBinder uiCompBinder)
    {
        if (File.Exists(uiCompBinder.binderExportPath)) File.Delete(uiCompBinder.binderExportPath);
        Directory.CreateDirectory(Path.GetDirectoryName(uiCompBinder.binderExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();
        generator.AddLine("// This file was automatically generated by UIGenerator.cs");
        generator.AddLine($"// {uiCompBinder.binderExportPath.Replace('\\', '/')}");
        generator.AddLine("using UnityEngine.UI;");

        generator.AddLine();

        using (generator.AddBlock($"public class {uiCompBinder.binderClsName} : UIBinderBase")) {
            var uiBinderTypes = TypeCache.GetTypesDerivedFrom(typeof(UIBinderBase));
            var uiLogicTypes = TypeCache.GetTypesDerivedFrom(typeof(UILogicBase));
            foreach (var node in uiCompBinder.nodeList) {
                if (node.value is UIComponentBinder childBinder) {
                    Type binderType = uiBinderTypes.FirstOrDefault(t => t.Name == childBinder.binderClsName);
                    Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == childBinder.logicClsName);
                    if (binderType != null && logicType != null && childBinder.GetComponent(binderType) != null) {
                        generator.AddLine($"public {logicType.Name} {node.name};");
                    }
                } else {
                    generator.AddLine($"public {node.value.GetType().Name} {node.name};");
                }
            }
        }

        using (var writer = new StreamWriter(uiCompBinder.binderExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }

    private static void ExportUILogic(UIComponentBinder uiCompBinder)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(uiCompBinder.logicExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();

        string uiType = uiCompBinder.isPage ? "UIPageWithBinder" : "UIWidgetWithBinder";
        using (generator.AddBlock($"public class {uiCompBinder.logicClsName} : {uiType}<{uiCompBinder.binderClsName}>")) {

        }

        using (var writer = new StreamWriter(uiCompBinder.logicExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }
}
