using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

public static class UIGenerator
{
    public static void ExportUIScripts(UIComponentBinder uiCompBinder)
    {
        ExportUIBinder(uiCompBinder);
        if (!File.Exists(uiCompBinder.logicExportPath)) {
            ExportUILogic(uiCompBinder);
        }

        AssetDatabase.Refresh();
    }

    private static void ExportUIBinder(UIComponentBinder uiCompBinder)
    {
        if (File.Exists(uiCompBinder.binderExportPath)) File.Delete(uiCompBinder.binderExportPath);
        Directory.CreateDirectory(Path.GetDirectoryName(uiCompBinder.binderExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();
        generator.AddLine("// This file was automatically generated by UIGenerator.cs");
        generator.AddLine($"// {uiCompBinder.binderExportPath.Replace('\\', '/')}");
        generator.AddLine("using UnityEngine.UI;");

        generator.AddLine();

        using (generator.AddBlock($"public class {uiCompBinder.binderClsName} : UIBinderBase")) {
            var uiBinderTypes = TypeCache.GetTypesDerivedFrom(typeof(UIBinderBase));
            var uiLogicTypes = TypeCache.GetTypesDerivedFrom(typeof(UILogicBase));
            List<(string, UIComponentBinder)> widgetBinders = new List<(string, UIComponentBinder)>();
            foreach (var node in uiCompBinder.nodeList) {
                if (node.value is UIComponentBinder childBinder) {
                    Type binderType = uiBinderTypes.FirstOrDefault(t => t.Name == childBinder.binderClsName);
                    Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == childBinder.logicClsName);
                    if (binderType != null && logicType != null && childBinder.GetComponent(binderType) != null) {
                        generator.AddLine($"public UIComponentBinder _{node.name};");
                        generator.AddLine($"public {logicType.Name} {node.name};");
                        widgetBinders.Add((node.name, childBinder));
                    }
                } else {
                    generator.AddLine($"public {node.value.GetType().Name} {node.name};");
                }
            }

            if (widgetBinders.Count > 0) {
                generator.AddLine();
                using (generator.AddBlock($"public override void InitWidgets()")) {
                    foreach (var (fieldName, binder) in widgetBinders) {
                        Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == binder.logicClsName);
                        if (logicType != null) {
                            generator.AddLine($"{fieldName} = new {binder.logicClsName}();");
                            generator.AddLine($"binderWidgets.Add({fieldName});");
                        }
                    }
                }
            }
        }

        using (var writer = new StreamWriter(uiCompBinder.binderExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }

    private static void ExportUILogic(UIComponentBinder uiCompBinder)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(uiCompBinder.logicExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();

        string uiType = uiCompBinder.isPage ? "UIPageWithBinder" : "UIWidgetWithBinder";
        using (generator.AddBlock($"public class {uiCompBinder.logicClsName} : {uiType}<{uiCompBinder.binderClsName}>")) {

        }

        using (var writer = new StreamWriter(uiCompBinder.logicExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }
}
