using System;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

public static class UIGenerator
{
    public readonly static string UI_SCRIPT_FOLDER_PATH = Path.Combine(Application.dataPath, "Scripts", "Game", "UI");
    public readonly static string UI_BINDER_EXPORT_PATH = Path.Combine(UI_SCRIPT_FOLDER_PATH, "Binder");
    public readonly static string UI_LOGIC_EXPORT_PATH = Path.Combine(UI_SCRIPT_FOLDER_PATH, "Logic");

    public static void ExportUIScripts(UIGenInfo uiGenInfo)
    {
        ExportUIBinder(uiGenInfo);
        if (!File.Exists(uiGenInfo.logicExportPath)) {
            ExportUILogic(uiGenInfo);
        }

        AssetDatabase.Refresh();
    }

    private static void ExportUIBinder(UIGenInfo uiGenInfo)
    {
        if (File.Exists(uiGenInfo.binderExportPath)) File.Delete(uiGenInfo.binderExportPath);
        Directory.CreateDirectory(Path.GetDirectoryName(uiGenInfo.binderExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();
        generator.AddLine("// This file was automatically generated by UIGenerator.cs");
        generator.AddLine($"// {uiGenInfo.binderExportPath.Replace('\\', '/')}");
        generator.AddLine("using UnityEngine.UI;");

        generator.AddLine();

        using (generator.AddBlock($"public class {uiGenInfo.binderClsName} : UILogicBinder")) {
            var uiLogicTypes = TypeCache.GetTypesDerivedFrom(typeof(UILogicBase));
            foreach (var node in uiGenInfo.binder.nodeList) {
                if (node.value is UIComponentBinder uiCompBinder) {
                    var nodeGenInfo = new UIGenInfo(uiCompBinder);
                    Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == nodeGenInfo.logicClsName);
                    if (logicType != null) {
                        generator.AddLine($"public {logicType.Name} {node.name};");
                    }
                } else {
                    generator.AddLine($"public {node.value.GetType().Name} {node.name};");
                }
            }
        }

        using (var writer = new StreamWriter(uiGenInfo.binderExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }

    private static void ExportUILogic(UIGenInfo uiGenInfo)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(uiGenInfo.logicExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();

        string uiType = uiGenInfo.isPage ? "UIPageWithBinder" : "UIWidgetWithBinder";
        using (generator.AddBlock($"public class {uiGenInfo.logicClsName} : {uiType}<{uiGenInfo.binderClsName}>")) {

        }

        using (var writer = new StreamWriter(uiGenInfo.logicExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }
}
