using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;

public static class UICodeGenerator
{
    public static void ExportUIScripts(UIBinderEditor uibinderEditor)
    {
        ExportUIBinder(uibinderEditor);
        if (!File.Exists(uibinderEditor.logicExportPath)) {
            ExportUILogic(uibinderEditor);
        }

        AssetDatabase.Refresh();
    }

    private static void ExportUIBinder(UIBinderEditor uiBinderEditor)
    {
        if (File.Exists(uiBinderEditor.binderExportPath)) File.Delete(uiBinderEditor.binderExportPath);
        Directory.CreateDirectory(Path.GetDirectoryName(uiBinderEditor.binderExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();
        generator.AddLine("// This file was automatically generated by UICodeGenerator.cs");
        generator.AddLine($"// {uiBinderEditor.binderExportPath.Replace('\\', '/')}");
        generator.AddLine("using TMPro;");
        generator.AddLine("using UnityEngine.UI;");

        generator.AddLine();

        using (generator.AddBlock($"public class {uiBinderEditor.binderClsName} : UIBinderBase")) {
            var uiBinderTypes = TypeCache.GetTypesDerivedFrom(typeof(UIBinderBase));
            var uiLogicTypes = TypeCache.GetTypesDerivedFrom(typeof(UILogicBase));
            List<(string, UIBinderEditor)> widgetBinderEditors = new List<(string, UIBinderEditor)>();
            foreach (var node in uiBinderEditor.nodeList) {
                if (node.value is UIBinderEditor childBinderEditor) {
                    Type binderType = uiBinderTypes.FirstOrDefault(t => t.Name == childBinderEditor.binderClsName);
                    Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == childBinderEditor.logicClsName);
                    if (binderType != null && logicType != null && childBinderEditor.GetComponent(binderType) != null) {
                        generator.AddLine($"public UIBinderEditor _{node.name};");
                        generator.AddLine($"public {logicType.Name} {node.name};");
                        widgetBinderEditors.Add((node.name, childBinderEditor));
                    } else {
                        Logger.LogError("Child widget binder script not attached!", ("widgetLogicType", logicType.Name));
                    }
                } else {
                    generator.AddLine($"public {node.value.GetType().Name} {node.name};");
                }
            }

            if (widgetBinderEditors.Count > 0) {
                generator.AddLine();
                using (generator.AddBlock($"public override void InitWidgets(UILogicBase owner)")) {
                    generator.AddLine("base.InitWidgets(owner);");
                    foreach (var (fieldName, binder) in widgetBinderEditors) {
                        Type logicType = uiLogicTypes.FirstOrDefault(t => t.Name == binder.logicClsName);
                        if (logicType != null) {
                            generator.AddLine($"{fieldName} = UIWidget.CreateWidgetInstance<{binder.logicClsName}>(owner);");
                            generator.AddLine($"binderWidgets.TryAdd(_{fieldName}.name, {fieldName});");
                            generator.AddLine($"binderWidgetGOs.TryAdd(_{fieldName}.name, _{fieldName}.gameObject);");
                        }
                    }
                }
            }
        }

        using (var writer = new StreamWriter(uiBinderEditor.binderExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }

    private static void ExportUILogic(UIBinderEditor uiBinderEditor)
    {
        Directory.CreateDirectory(Path.GetDirectoryName(uiBinderEditor.logicExportPath));

        CSCodeGenerator generator = new CSCodeGenerator();

        if (uiBinderEditor.isPage) {
            using (generator.AddBlock($"public class {uiBinderEditor.logicClsName} : UIPageWithBinder<{uiBinderEditor.binderClsName}>")) {
                generator.AddLine($"public override string pageName => UIPage.GetPageName<{uiBinderEditor.logicClsName}>();");
            }
        } else {
            using (generator.AddBlock($"public class {uiBinderEditor.logicClsName} : UIWidgetWithBinder<{uiBinderEditor.binderClsName}>")) {
                generator.AddLine($"public override string widgetName => UIWidget.GetWidgetName<{uiBinderEditor.logicClsName}>();");
            }
        }

        using (var writer = new StreamWriter(uiBinderEditor.logicExportPath, false, Encoding.UTF8)) {
            writer.Write(generator.OutputCode());
            writer.Flush();
        }
    }
}
